Test Client Upgrade
TeselaGen/api-client pull request #2
Opened 2020-12-02 18:54 UTC by AndresPerezTesela

- Fixed client.login apiKey support
- Enhanced test importer endpoints

2020-12-04 23:59 UTC, diegovalenzuelaiturra commented
We could add a pre-commit hook to include the YAPF formatter before merging this into master

2020-12-07 13:47 UTC, AndresPerezTesela commented
> We could add a pre-commit hook to include the YAPF formatter before merging this into master (and include a fixed YAPF version in the requirements file)

Yes! I agree. However since this is a public repo, maybe we could use a github action to do this 🤔

2020-12-19 09:23 UTC, diegovalenzuelaiturra commented
Looks ok

2020-12-22 17:08 UTC, diegovalenzuelaiturra commented
I've doing the following :

```bash
cd ~/Documents/GitHub/

# clone repo
git clone git@github.com:TeselaGen/api-client.git
```

Then,

```bash
# go to repo dir
cd ~/Documents/GitHub/api-client

# checkout to PR branch
git checkout feature/test-client-importer-upgrades

# fetch and pull current changes
git fetch && git pull

```

After that, I've run

```bash
# cd to docker env dir
cd ~/Documents/GitHub/api-client/docker_environment

# run script
bash remove_build_run.sh
```

And, when it is running the following command (from the `Dockerfile`)

```Dockerfile
RUN cd lib/ && python setup.py install && cd ..
```

It shows the following warning

```diff
- WARNING: The wheel package is not available.
```

Which I suspect could be solved by adding one of following alternatives to the `Dockerfile`

```Dockerfile
# Dockerfile, before installing the package
RUN python3 -m pip install wheel --upgrade
```

```Dockerfile
# Dockerfile, before installing the package
RUN python3 -m pip install wheel==0.36.2
```

Or, by including it to the `requirements.txt` 

```python3
# requirements.txt
wheel==0.36.2
```

2020-12-22 17:23 UTC, diegovalenzuelaiturra commented
Also, I've noticed we are pulling from an "old" ubuntu image, here

https://github.com/TeselaGen/api-client/blob/5056d5516a37e298753bd992b5c87ef35cd7a752/docker_environment/Dockerfile#L1-L4

We could pull a more "recent" one, by modifying it to

```Dockerfile
ARG BASE_CONTAINER=ubuntu:bionic-20201119@sha256:a7fa45fb43d471f4e66c5b53b1b9b0e02f7f1d37a889a41bbe1601fac70cb54e
```

2020-12-22 17:29 UTC, AndresPerezTesela commented
> ```dockerfile
> ubuntu:bionic-20201119@sha256:a7fa45fb43d471f4e66c5b53b1b9b0e02f7f1d37a889a41bbe1601fac70cb54e
> ```

Issue created for this: https://github.com/TeselaGen/api-client/issues/4

2020-12-22 17:36 UTC, diegovalenzuelaiturra commented
Also, when excecuting the library installation, it shows the following message, related to the [zip_flag](http://peak.telecommunity.com/DevCenter/setuptools#setting-the-zip-safe-flag)

```diff
- zip_safe flag not set; analyzing archive contents...
- teselagen.utils.__pycache__.utils.cpython-36: module references __path__
```

I think it's currently safe, but to control this behaviour, we could pass it as an argument to the `setup(...)` method in `setup.py`, and set it to e.g. `setup(zip_safe=False, ...)`

https://github.com/TeselaGen/api-client/blob/5056d5516a37e298753bd992b5c87ef35cd7a752/lib/setup.py#L62-L71

2020-12-22 20:10 UTC, diegovalenzuelaiturra commented
Currently, when the client has been installed in `install` mode (which would be the case for a common user who has installed the package), the path to the library would be something like the following

```bash
/usr/local/lib/python3.6/dist-packages/teselagen-20.48.2-py3.6.egg/teselagen
```

Which can be checked by running the following command (e.g. from `/home` directory )

```bash
bash -c "python3 -c 'import teselagen; print(teselagen.__path__[0])'"
```


I've created this tiny script to optionally add `.credentials` and `.test_configuration` files


```python3
# /usr/bin/python3
import getpass
import json
import logging
from pathlib import Path
from typing import Dict

from teselagen.api.client import DEFAULT_HOST_URL
from teselagen.utils import get_credentials_path
from teselagen.utils import get_project_root
from teselagen.utils import get_test_configuration_path

logger = logging.getLogger(__name__)

# Paths
root_path: Path = get_project_root()
credentials_path: Path = get_credentials_path()
configuration_path: Path = get_test_configuration_path()

if input("login credentials ? [yes|no] : ").lower() in ["y", "yes"]:

    # login
    username: str = input("username : ")
    password: str = getpass.getpass(prompt="password : ")

    credentials: Dict[str, str] = {"username": username, "password": password}

    print(f"Saving credentials to : {credentials_path.absolute()}")

    logger.info(f"Saving credentials to : {credentials_path.absolute()}")

    json.dump(credentials,
              credentials_path.open("w", encoding="utf-8"),
              indent=4)

    del username, password, credentials

if input("test configuration ? [yes|no] : ").lower() in ["y", "yes"]:

    # test configuration
    host_url: str = input(f"host_url [default: {DEFAULT_HOST_URL}] : ")
    configuration: Dict[str, str] = {
        "host_url": host_url if host_url is not "" else DEFAULT_HOST_URL
    }

    print(f"Saving test configuration to : {configuration_path.absolute()}")

    logger.info(
        f"Saving test configuration to : {configuration_path.absolute()}")

    json.dump(configuration,
              configuration_path.open("w", encoding="utf-8"),
              indent=4)

    del host_url, configuration
```

After that, one could run the tests by running the following

```bash
# cd to library path
cd $(bash -c "python3 -c 'import sys; import teselagen; print(teselagen.__path__[0], file=sys.stdout)'")

# copy conftest.py
cp /tmp/lib/conftest.py ./conftest.py

pytest
```

2020-12-22 20:15 UTC, AndresPerezTesela commented
> Currently, when the client has been installed in `install` mode (which would be the case for a common user who has installed the package), the path to the library would be something like the following
> 
> ```shell
> /usr/local/lib/python3.6/dist-packages/teselagen-20.48.2-py3.6.egg/teselagen
> ```
> 
> Which can be checked by running the following command (e.g. from `/home` directory )
> 
> ```shell
> bash -c "python3 -c 'import teselagen; print(teselagen.__path__[0])'"
> ```
> 
> I've created this tiny script to optionally add `.credentials` and `.test_configuration` files to be used after the library is installed. If it makes sense, I could add it as a util to the library.
> 
> ```python
> # /usr/bin/python3
> import getpass
> import json
> import logging
> from pathlib import Path
> from typing import Dict
> 
> from teselagen.api.client import DEFAULT_HOST_URL
> from teselagen.utils import get_credentials_path
> from teselagen.utils import get_project_root
> from teselagen.utils import get_test_configuration_path
> 
> logger = logging.getLogger(__name__)
> 
> # Paths
> root_path: Path = get_project_root()
> credentials_path: Path = get_credentials_path()
> configuration_path: Path = get_test_configuration_path()
> 
> if input("login credentials ? [yes|no] : ").lower() in ["y", "yes"]:
> 
>     # login
>     username: str = input("username : ")
>     password: str = getpass.getpass(prompt="password : ")
> 
>     credentials: Dict[str, str] = {"username": username, "password": password}
> 
>     print(f"Saving credentials to : {credentials_path.absolute()}")
> 
>     logger.info(f"Saving credentials to : {credentials_path.absolute()}")
> 
>     json.dump(credentials,
>               credentials_path.open("w", encoding="utf-8"),
>               indent=4)
> 
>     del username, password, credentials
> 
> if input("test configuration ? [yes|no] : ").lower() in ["y", "yes"]:
> 
>     # test configuration
>     host_url: str = input(f"host_url [default: {DEFAULT_HOST_URL}] : ")
>     configuration: Dict[str, str] = {
>         "host_url": host_url if host_url is not "" else DEFAULT_HOST_URL
>     }
> 
>     print(f"Saving test configuration to : {configuration_path.absolute()}")
> 
>     logger.info(
>         f"Saving test configuration to : {configuration_path.absolute()}")
> 
>     json.dump(configuration,
>               configuration_path.open("w", encoding="utf-8"),
>               indent=4)
> 
>     del host_url, configuration
> ```
> 
> Save it and run it to add the mentioned configuration files.
> 
> After that, one could run the tests by running the following
> 
> ```shell
> # cd to library path
> cd $(bash -c "python3 -c 'import sys; import teselagen; print(teselagen.__path__[0], file=sys.stdout)'")
> 
> # copy conftest.py
> cp /tmp/lib/conftest.py ./conftest.py
> 
> pytest
> ```

looks good.

2020-12-22 20:22 UTC, diegovalenzuelaiturra commented
I've run the tests and they are fine.

```bash
python3 -m pip freeze | grep teselagen
>> teselagen==20.48.2
```

```bash
==================== 32 passed, 13 skipped, 3 warnings in 36.33s ====================
```

NOTE : I will add the script to configure this and re run the tests after that !

2020-12-22 20:33 UTC, diegovalenzuelaiturra commented
To run tests in `develop/editable` mode, I've done the following

```bash
cd ~/Documents/GitHub/api-client

# checkout to PR branch
git checkout feature/test-client-importer-upgrades

# fetch and pull current changes
git fetch && git pull

# cd to docker environment
cd ~/Documents/GitHub/api-client/docker_environment

# stop and remove the container 
docker stop tgclient
docker rm -f tgclient

# start container dev
bash run_dev.sh

# connect to container
docker exec --tty --interactive tgclient bash

# cd to library (editable mode)
cd /home/development/lib
```

Set the needed `.credentials` and `.test_configuration`

Then, run the tests

```bash
cd /home/development/lib

# run tests
python3 setup.py test
```

2020-12-22 20:42 UTC, diegovalenzuelaiturra requested changes, later dismissed
I've added some comments to be addressed

2020-12-22 20:42 UTC, diegovalenzuelaiturra commented on lib/teselagen/api/test_client.py
> +        """
We should fix the documentation and/or type annotations for this method, so they don't mismatch.

2020-12-22 20:42 UTC, diegovalenzuelaiturra commented on lib/teselagen/api/client.py
> +
Since both, `password` and `apiKey` arguments are not required simultaneously, we should fix the documentation for the `login` method, because it may be misleading (even though, they are annotated as optionals).

For example, regarding to the `password` argument, it now says :

```python3
- A password is required and will be prompted.
- If not provided it will be prompted.
```

Which by looking at the following line, does not happen when an `apiKey` has been provided.

```python3
_password = apiKey if apiKey is not None else password
```

2020-12-22 21:50 UTC, diegovalenzuelaiturra commented
I've tested against `"host_url" : "https://platform-prerelease.teselagen.com"` and some tests failed

```python
[gw4] [ 63%] FAILED teselagen/api/tests/notebooks/CRISPR Tool.ipynb::nbregression(CRISPR Tool)
[gw5] [ 65%] FAILED teselagen/api/tests/notebooks/Hello_World_TEST_module.ipynb::nbregression(Hello_World_TEST_module)
```

```bash
============ 2 failed, 32 passed, 13 skipped, 20 warnings in 21.78s ============
```

2020-12-23 02:44 UTC, juanneilson requested changes
I think is not a good idea to have duplicated notebooks just for testing. Maybe we should just omit some notebooks from the test if we need to. We can do it by using this configuration option:
https://github.com/TeselaGen/api-client/blob/953a3f41dd885a889d4db64275adcad640565ff3/lib/setup.cfg#L13
and adding some prefix or suffix to notebooks names that are going to be tested, such us QA or PYTESTED, an changing the pattern to something like:
`nb_file_fnmatch = teselagen/api/tests/notebooks/*PYTESTED.ipynb`
Or... a Pytested folder inside Examples, but avoiding code duplication

2020-12-23 13:36 UTC, AndresPerezTesela commented
> I think is not a good idea to have duplicated notebooks just for testing. Maybe we should just omit some notebooks from the test if we need to. We can do it by using this configuration option:
> https://github.com/TeselaGen/api-client/blob/953a3f41dd885a889d4db64275adcad640565ff3/lib/setup.cfg#L13
> 
> 
> and adding some prefix or suffix to notebooks names that are going to be tested, such us QA or PYTESTED, and changing the pattern accordingly, for example to something like:
> `nb_file_fnmatch = teselagen/api/tests/notebooks/*PYTESTED.ipynb`
> Or... a Pytested folder inside Examples, but avoiding code duplication

Yeah, suffix sounds good too or also putting pytested notebooks inside a specific folder for the pattern to recognize.

2020-12-23 14:06 UTC, AndresPerezTesela commented
Tests passed in platform-prerelease
================= 34 passed, 13 skipped, 20 warnings in 20.02s =================

2020-12-23 20:43 UTC, juanneilson approved these changes

2020-12-23 20:44 UTC, merged