Update environments, configurations and scripts.
TeselaGen/api-client pull request #29
Opened 2021-11-09 01:41 UTC by diegovalenzuelaiturra

Closes https://github.com/TeselaGen/api-client/issues/28

2021-12-03 20:46 UTC, juanneilson reviewed
We should consider looking into notebooks tests that fail against `platform`:
```
FAILED teselagen/examples/pytested/Closing-the-DBTL-Cycle.ipynb::nbregression(Closing-the-DBTL-Cycle)
FAILED teselagen/examples/pytested/Hello-World-TEST-module.ipynb::nbregression(Hello-World-TEST-module)
```

2021-12-03 20:46 UTC, juanneilson commented on teselagen/api/tests/test_multiomics.py
> +        #                          "Please, contact the TeselaGen team for more information. "))
Is this currently valid?

2021-12-06 19:24 UTC, juanneilson commented
Check why are failing the notebooks (against `platform` and `RC`) and `get_models_by_type` (against RC)

2021-12-28 07:42 UTC, diegovalenzuelaiturra commented
- [x] `teselagen/api/tests/test_discover_client.py::TestDISCOVERClient::test_get_models_by_type[evolutive]`

- [x] `teselagen/api/tests/test_test_client.py::TestTESTClient::test_download_file`

- [ ] `teselagen/api/tests/test_discover_client.py::TestDISCOVERClient::test_get_model_submit_get_cancel_delete`

- [ ] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_optical_density_upload`

- [ ] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_upload_external_metabolites`

- [ ] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_download_file`

- [ ] `teselagen/examples/pytested/Closing-the-DBTL-Cycle.ipynb::nbregression(Closing-the-DBTL-Cycle)`
    - -> `OSError: Didn't found model`

2021-12-28 10:16 UTC, diegovalenzuelaiturra commented
Cleaning up some test files and assays before the test run starts fixes most of the tests that were broken. 

- [x] `teselagen/api/tests/test_discover_client.py::TestDISCOVERClient::test_get_models_by_type[evolutive]`

- [x] `teselagen/api/tests/test_test_client.py::TestTESTClient::test_download_file`

- [x] `teselagen/api/tests/test_discover_client.py::TestDISCOVERClient::test_get_model_submit_get_cancel_delete`
    - `Exception: Got code : 500. Reason : Internal Server Error`

- [x] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_optical_density_upload`
    - `AssertionError: Expecting just one assay for this assertion`
    - `assert 2 == 1`

- [x] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_upload_external_metabolites`
    - `AssertionError: Expecting just one assay for this assertion`
    - `assert 2 == 1`

- [x] `teselagen/api/tests/test_multiomics.py::TestTESTClientMultiomicsData::test_download_file`
    - `AssertionError: Wrong shape`
    - `assert (0, 8) == (10, 5)`

The following test has not been fixed yet
- [ ] `teselagen/examples/pytested/Closing-the-DBTL-Cycle.ipynb::nbregression(Closing-the-DBTL-Cycle)`
    - `OSError: Didn't found model`

2021-12-28 15:44 UTC, juanneilson requested changes

2021-12-28 15:44 UTC, juanneilson commented on teselagen/examples/pytested/Hello-World-TEST-module.ipynb
>      "filepath = str(get_project_root() / \"teselagen/examples/test_module_example.csv\")\n",
```suggestion
    "filepath = str(get_project_root() / \"teselagen/api/tests/example_file.csv\")\n",
```

2021-12-28 16:05 UTC, diegovalenzuelaiturra commented on teselagen/examples/pytested/Hello-World-TEST-module.ipynb
>      "filepath = str(get_project_root() / \"teselagen/examples/test_module_example.csv\")\n",
done

2021-12-28 19:24 UTC, juanneilson approved these changes

2021-12-28 19:38 UTC, AndresPerezTesela approved these changes

2021-12-28 19:44 UTC, merged